name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Build with dotnet
      run: dotnet msbuild KeraLua.sln -p:Configuration=Release
    - name: Pack nuget package
      run: nuget pack KeraLua.nuspec
    - name: Upload KeraLua artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: KeraLua        
        path: lib\Release\net45
    - name: Upload runtimes artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Runtimes        
        path: runtimes
