name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet msbuild KeraLua.sln -p:Configuration=Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: KeraLua        
        path: lib\Release\net45
