name: Deploy

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Buerkert/index.json -Username Buerkert -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push KeraLua\bin\Release\Buerkert.KeraLua.*.nupkg -Source "GPR"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: KeraLua
        path: KeraLua\bin\Release\*nupkg

